### PR TITLE
Show name of TA who answered question for all questions

### PR DESCRIPTION
**Pull request by KeenWill**

### CODE REVIEW

**Comment by conswang** [comment]
I can merge this in as a quick fix for now, but not sure the design is most optimal
@linda-ting maybe we want to move the answering TA somewhere else onto the question card?

Test in 3 browser sessions - student, TA 1 who is answering, TA 2 who can see who is answering

TA 1 view
image

TA 2 view
image

TA 1 (zoom link)
image

TA 2 (zoom link)
image

**Comment by KeenWill** [comment]
Rebasing from master once #145 is merged should get backend CI to pass.

**Comment by linda-ting** [comment]
I think it might be better to move the answering TA's name down next to the action buttons, and to change the card color depending on status (i.e. green if you are answering, red if unanswered, blue if someone else is answering). 

Screen Shot 2021-09-23 at 9 40 17 AM

**Comment by conswang** [comment]
With zoom link (other TA)
image

With zoom link (answering TA)
image

Without zoom link (answering TA)
image

Without zoom link (other TA)
image

**Review by linda-ting — APPROVED** [review]

**Pull request merged**
